### ISSUE TITLE
Running HoneyCome on Android winlator, error loading WebRequestBlocker

### ISSUE THREAD

**Issue by lichuang9** [ManlyMarco/HC-HF_Patch#5]
Running HoneyCome on Android winlator, error loading WebRequestBlocker

I'm IQOO NEO10 8GEN3,
I'm running HoneyCome on winlator,
BepInEx loaded WebRequestBlocker with error, works fine on PC with no error
Log:

[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   :AssemblyPatcher] Loaded 1 patcher type from [CultureFix_IL2CPP 21.6.0.0]
[Info   :AssemblyPatcher] Loaded 1 patcher type from [IMGUIModule.Il2Cpp.CoreCLR.Patcher 1.0.0.0]
[Info   : Preloader] 2 patcher plugins loaded
[Info   : Preloader] 2 assemblies discovered
[Info   :CultureFix] CultureFix - Forcing process culture to ja-JP.
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 4 plugins to load
[Info   :   BepInEx] Loading [Configuration Manager 18.3.0]
[Info   :Il2CppInterop] Registered mono type ConfigurationManager.ConfigurationManager+ConfigurationManagerBehaviour in il2cpp domain
[Info   :   BepInEx] Loading [BGM Loader 20.0.0]
[Info   :BGM Loader] Found 0 custom intro clips
[Info   :   BepInEx] Loading [Configuration Manager wrapper for HoneyCome 20.0.0]
[Info   :Il2CppInterop] Registered mono type ConfigurationManagerWrapper.ConfigurationManagerWrapper+MonoBehaviour in il2cpp domain
[Info   :   BepInEx] Loading [WebRequestBlocker 1.1.2]
[Error  :   BepInEx] Error loading [WebRequestBlocker 1.1.2]: System.Net.HttpListenerException (3): Path not found.
   at System.Net.HttpListenerSession..ctor(HttpListener listener)
   at System.Net.HttpListener.Start()
   at WebRequestBlocker.Plugin.Hooks.InstallHooks()
   at WebRequestBlocker.Plugin.Load()
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.LoadPlugin(PluginInfo pluginInfo, Assembly pluginAssembly) in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/IL2CPPChainloader.cs:line 136
   at BepInEx.Bootstrap.BaseChainloader`1.LoadPlugins(IList`1 plugins) in /home/runner/work/BepInEx/BepInEx/BepInEx.Core/Bootstrap/BaseChainloader.cs:line 411
[Message:   BepInEx] Chainloader startup complete
[Error  :BGM Loader] Failed to play custom intro clip - System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at BGMLoader.BGMLoader.TitleCallOverride(Loader loader) in D:\SVN\BepisPlugins\src\HC_BGMLoader\Core.BGMLoader.cs:line 49

![QQ图片20241211095128](https://github.com/user-attachments/assets/d690c723-cc54-4f18-99ed-b84d2bd0f3f2)
![QQ图片20241211095138](https://github.com/user-attachments/assets/6b367c2d-1910-4d81-a644-b7fd0ab3e15d)
![QQ图片20241211095146](https://github.com/user-attachments/assets/94b963a1-3ed9-4e4c-a289-550df975206a)
![QQ图片20241211095645](https://github.com/user-attachments/assets/a952e540-802e-4685-8a79-378a7abe4211)
![QQ图片20241211095152](https://github.com/user-attachments/assets/f172f1b4-70e4-46bc-a8d1-21311911920a)

**Comment by lichuang9** [comment]
Unity games need to be launched with -force-gfx-direct

**Comment by ManlyMarco** [comment]
Sadly I don't think I can help you with this, I don't even have any way of testing it.

**Comment by lichuang9** [comment]
> Sadly I don't think I can help you with this, I don't even have any way of testing it.

Winlator requires Snapdragon 870 or above processor, container configuration Turnip and DXVK, and box64 performance selection
All games need to fix the registry  HKEY_CURRENT_USER\SOFTWARE\ ***, and there must be a file  .\UserData\setup.xml 
Starting the game: Except for PlayHome, all other games require single threaded startup, for example: HoneySelect2.exe -force-gfx-direct


To start InitSetting. exe, it is necessary to install Wine Momo 
To start BepInE, the wine configuration library needs to add winhttp.dll

runs PlayHome:
https://github.com/user-attachments/assets/4ce8dc6e-412b-474a-927f-c76e0b145ffa

runs HoneySelect2:
https://github.com/user-attachments/assets/2252cbae-a5e1-4096-89ea-22f7856f15cf

runs RoomGirl:
https://github.com/user-attachments/assets/487a1059-1088-4a99-984b-005834ca2ca3

runs HoneyCome:
https://github.com/user-attachments/assets/a3bdb66c-bed0-4cec-ab12-663f021caddf

**Comment by ManlyMarco** [comment]
Sorry, I don't think I will work on fixing this issue. If someone makes a fixed version of WebRequestBlocker I will include it in the patch. I suggest asking in the Koikatsu discord server for further help or if anyone wants to try fixing the plugin.
